const crypto = require('crypto');

/**
 * Generates 6 unique draw numbers from 1 to 49 deterministically from a combined seed.
 * Saves seed, salt, and final hash for audit verification trails.
 */
function generateDrawNumbers(lotteryName, drawId, salt) {
  const seedSuffix = crypto.randomBytes(16).toString('hex');
  const combinedSeed = `${lotteryName}-${drawId}-${salt}-${seedSuffix}`;
  
  const drawNumbers = [];
  let ballIndex = 1;
  let retryIndex = 0;

  while (drawNumbers.length < 6) {
    // Generate deterministic hash for the specific ball number
    const inputString = `${combinedSeed}-ball-${ballIndex}${retryIndex > 0 ? `-retry-${retryIndex}` : ''}`;
    const hash = crypto.createHmac('sha256', salt).update(inputString).digest('hex');
    
    // Parse hex characters into integer and bounds to 1 - 49
    const number = (parseInt(hash.substring(0, 12), 16) % 49) + 1;
    
    if (!drawNumbers.includes(number)) {
      drawNumbers.push(number);
      ballIndex++;
      retryIndex = 0; // Reset collision retries
    } else {
      retryIndex++; // Try again with modified seed if collision occurs
    }
  }

  // Sort numbers in ascending order
  drawNumbers.sort((a, b) => a - b);

  // Compute master hash for audit purposes
  const masterHash = crypto.createHmac('sha256', salt).update(combinedSeed).digest('hex');

  return {
    winningNumbers: drawNumbers,
    seed: combinedSeed,
    hash: masterHash
  };
}

/**
 * Verifies that the winningNumbers exactly match the output generated by the combinedSeed and salt.
 */
function verifyDrawNumbers(combinedSeed, salt, winningNumbers) {
  const drawNumbers = [];
  let ballIndex = 1;
  let retryIndex = 0;

  while (drawNumbers.length < 6) {
    const inputString = `${combinedSeed}-ball-${ballIndex}${retryIndex > 0 ? `-retry-${retryIndex}` : ''}`;
    const hash = crypto.createHmac('sha256', salt).update(inputString).digest('hex');
    const number = (parseInt(hash.substring(0, 12), 16) % 49) + 1;
    
    if (!drawNumbers.includes(number)) {
      drawNumbers.push(number);
      ballIndex++;
      retryIndex = 0;
    } else {
      retryIndex++;
    }
  }
  drawNumbers.sort((a, b) => a - b);

  // Verify elements match
  if (drawNumbers.length !== winningNumbers.length) return false;
  return drawNumbers.every((val, index) => val === winningNumbers[index]);
}

module.exports = {
  generateDrawNumbers,
  verifyDrawNumbers
};
